#!/bin/bash
# smoke-test.sh - Dhunter MVP 端到端 smoke test
# 启动顺序: dhunter-mcp (9124) → Python agent (9100) → Dhunter server (13343)
# 用法: ./scripts/smoke-test.sh
set -u

PLAT="http://127.0.0.1:13343"
AGENT="http://127.0.0.1:9100"
MCP="http://127.0.0.1:9124"

# Tokens are generated by start-dhunter.sh into .dhunter.tokens.
TOKEN_FILE="$(cd "$(dirname "$0")/.." && pwd)/.dhunter.tokens"
if [ -f "$TOKEN_FILE" ]; then
  # shellcheck disable=SC1090
  source "$TOKEN_FILE"
else
  WTOK="dhunter-mcp-please-change"
  PLAT_TOKEN="dhunter-admin-please-change-me"
fi
# Admin 密码从启动日志拿(每次启动都重置)
ADMIN_PW=$(grep "password:" /tmp/dhunter-server.log 2>/dev/null | head -1 | awk '{print $2}')
if [ -z "$ADMIN_PW" ]; then
  ADMIN_PW="$PLAT_TOKEN"  # fallback: yaml 配的 password
fi
echo "admin pw: $ADMIN_PW"

ok=0; fail=0
check() {
  local name="$1"; shift
  local cond="$1"; shift
  if [ "$cond" = "ok" ]; then
    printf "  ✅ %s\n" "$name"
    ok=$((ok+1))
  else
    printf "  ❌ %s\n" "$name"
    fail=$((fail+1))
  fi
}
sec() { printf "\n\033[1;36m=== %s ===\033[0m\n" "$1"; }

# 1. 平台基础
sec "1. Dhunter 平台 (13343)"
status=$(curl -sS -o /dev/null -w "%{http_code}" $PLAT/api/healthz)
[ "$status" = "200" ] && check "/api/healthz" ok || check "/api/healthz ($status)" fail

# 2. MCP 工具
sec "2. dhunter-mcp (9124)"
H=$(curl -sS $MCP/healthz 2>&1)
echo "  /healthz: $H"
echo "$H" | grep -q '"dhunter-mcp"' && check "MCP service = dhunter-mcp (去特征)" ok || check "MCP service" fail
T=$(curl -sS -X POST -H "Authorization: Bearer $WTOK" -H "Content-Type: application/json" \
  -d '{"jsonrpc":"2.0","id":1,"method":"tools/list"}' $MCP/message)
TC=$(echo "$T" | python3 -c "import json,sys;d=json.load(sys.stdin);print(len(d.get('result',{}).get('tools') or []))" 2>/dev/null)
[ "$TC" -ge 20 ] && check "tools/list ($TC 个)" ok || check "tools/list ($TC)" fail
# strip prefix test
S=$(curl -sS -X POST -H "Authorization: Bearer $WTOK" -H "Content-Type: application/json" \
  -d '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"dhunter__risk_score","arguments":{"impact":"high","evidence":"smoke"}}}' \
  $MCP/message)
echo "$S" | grep -qE 'score[^0-9]+[0-9]+' && check "strip __ 前缀 (dhunter__risk_score)" ok || check "strip" fail

# 3. Python agent
sec "3. Python agent (9100)"
H=$(curl -sS $AGENT/healthz 2>&1)
echo "  /healthz: $H"
echo "$H" | grep -q '"ok":true' && check "agent healthz" ok || check "agent healthz ($H)" fail
RZ=$(curl -sS $AGENT/readyz 2>&1)
TC2=$(echo "$RZ" | python3 -c "import json,sys;d=json.load(sys.stdin);print(d.get('tool_count',0))" 2>/dev/null)
[ "$TC2" -ge 22 ] && check "agent readyz (tool_count=$TC2)" ok || check "agent readyz ($TC2)" fail

# 4. 平台鉴权 + target 解析
sec "4. 平台鉴权 + target 解析"
LOGIN=$(curl -sS -X POST -H "Content-Type: application/json" \
  -d "{\"username\":\"admin\",\"password\":\"$ADMIN_PW\"}" \
  $PLAT/api/auth/login 2>&1)
TOKEN=$(echo "$LOGIN" | python3 -c "import sys,json;d=json.load(sys.stdin);print(d.get('token',''))" 2>/dev/null)
[ -n "$TOKEN" ] && check "admin 登录拿 token" ok || { check "admin 登录 ($LOGIN)" fail; exit 1; }
# company
TGT=$(curl -sS -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
  -d '{"input":"Acme Corp","type":"auto"}' $PLAT/api/targets)
TY=$(echo "$TGT" | python3 -c "import sys,json;d=json.load(sys.stdin);print(d.get('type',''))" 2>/dev/null)
[ "$TY" = "company" ] && check "company 解析" ok || check "company 解析 ($TGT)" fail
# domain
TGT=$(curl -sS -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
  -d '{"input":"example.com","type":"auto"}' $PLAT/api/targets)
TY=$(echo "$TGT" | python3 -c "import sys,json;d=json.load(sys.stdin);print(d.get('type',''))" 2>/dev/null)
[ "$TY" = "domain" ] && check "domain 解析" ok || check "domain 解析 ($TGT)" fail
# url
TGT=$(curl -sS -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
  -d '{"input":"https://example.com/foo","type":"auto"}' $PLAT/api/targets)
TY=$(echo "$TGT" | python3 -c "import sys,json;d=json.load(sys.stdin);print(d.get('type',''))" 2>/dev/null)
[ "$TY" = "url" ] && check "url 解析" ok || check "url 解析 ($TGT)" fail
# ip
TGT=$(curl -sS -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
  -d '{"input":"1.2.3.4","type":"auto"}' $PLAT/api/targets)
TY=$(echo "$TGT" | python3 -c "import sys,json;d=json.load(sys.stdin);print(d.get('type',''))" 2>/dev/null)
[ "$TY" = "ip" ] && check "ip 解析" ok || check "ip 解析 ($TGT)" fail

# 5. 写漏洞 (单条)
sec "5. 写漏洞 (直接 API)"
TID=$(curl -sS -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
  -d '{"input":"example.com","type":"auto"}' $PLAT/api/targets | python3 -c "import sys,json;print(json.load(sys.stdin)['id'])")
RID=$(curl -sS -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
  -d "{\"target_id\":\"$TID\",\"objective\":\"smoke\"}" $PLAT/api/runs | python3 -c "import sys,json;print(json.load(sys.stdin)['run_id'])")
V=$(curl -sS -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
  -d "{\"run_id\":\"$RID\",\"title\":\"smoke vuln\",\"severity\":\"low\",\"target\":\"https://example.com\",\"evidence\":\"smoke test\"}" \
  $PLAT/api/vulnerabilities)
VID=$(echo "$V" | python3 -c "import json,sys;print(json.load(sys.stdin).get('id',''))" 2>/dev/null)
[ -n "$VID" ] && check "POST /api/vulnerabilities 创建" ok || check "POST /api/vulnerabilities ($V)" fail
# list
VL=$(curl -sS -H "Authorization: Bearer $TOKEN" "$PLAT/api/vulnerabilities?run_id=$RID")
COUNT=$(echo "$VL" | python3 -c "import json,sys;d=json.load(sys.stdin);print(len(d.get('vulnerabilities') or []))" 2>/dev/null)
[ "$COUNT" -ge 1 ] && check "GET /api/vulnerabilities 拿回 (count=$COUNT)" ok || check "GET /api/vulnerabilities ($COUNT)" fail
# report
RP=$(curl -sS -H "Authorization: Bearer $TOKEN" "$PLAT/api/runs/$RID/report")
echo "$RP" | grep -q "Dhunter Penetration Test Report" && check "Markdown 报告" ok || check "report ($RP)" fail

# 6. LLM 端到端
sec "6. 端到端 LLM (单 agent + MCP)"
RID2=$(curl -sS -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
  -d "{\"target_id\":\"$TID\",\"objective\":\"用 write_finding 写一条发现 (smoke test)\"}" \
  $PLAT/api/runs | python3 -c "import sys,json;print(json.load(sys.stdin)['run_id'])")
echo "  RID2: $RID2"
echo "  等 agent 跑完 (max 90s)..."
for i in $(seq 1 18); do
  sleep 5
  ST=$(curl -sS -H "Authorization: Bearer $TOKEN" "$PLAT/api/runs/$RID2" 2>/dev/null | python3 -c "import sys,json;print(json.load(sys.stdin).get('status',''))" 2>/dev/null)
  if [ "$ST" = "completed" ] || [ "$ST" = "failed" ]; then
    echo "  agent done in ${i}*5s, status=$ST"
    break
  fi
done
# 验证
MSGS=$(curl -sS -H "Authorization: Bearer $TOKEN" "$PLAT/api/runs/$RID2/messages" | python3 -c "
import json, sys
from collections import Counter
d = json.load(sys.stdin)
msgs = d.get('messages') or []
c = Counter(m.get('event_type') for m in msgs)
print(c.get('tool_call', 0) + c.get('tool_result', 0) + c.get('response_delta', 0) + c.get('message_done', 0))
")
[ "$MSGS" -ge 3 ] && check "messages 落库 (multi-type=$MSGS)" ok || check "messages ($MSGS)" fail

# 总结
sec "📊 Smoke Test 总结"
printf "  ✅ %d  passed\n" "$ok"
printf "  ❌ %d  failed\n" "$fail"
[ "$fail" -eq 0 ] && printf "\n  🎉 所有模块跑通!\n" || printf "\n  ⚠️  有 %d 个失败,看上面修\n" "$fail"
exit "$fail"
